services:
  app:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      FLASK_APP: app/app.py
      FLASK_ENV: development

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres-data:
