version: "3.8"
services:
  app:
    image: python:3.9-slim
    command: /bin/sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --debug"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      FLASK_APP: app/app.py
      FLASK_ENV: development
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:latest

  celery:
    image: python:3.9-slim
    command: /bin/sh -c "pip install -r /app/requirements.txt" && celery -A app.tareas.tareas worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres-data:
