services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    build: .
    ports:
      - "${HOST_PORT:-5000}:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      FLASK_APP: api.py
      FLASK_ENV: development

  worker:
    build: .
    command: celery -A app_worker.celery worker -l error --events

    depends_on:
      rabbitmq:
        condition: service_healthy
